spring:
  resources:
    static-locations:
      - file:hashtagmap-admin/src/main/resources/static
  profiles:
    active: local
    include: >
      kakao,
      kakao-security,
      db
  mvc:
    view:
      suffix: .html
---
spring:
  profiles: local
  resources:
    static-locations:
      - file:hashtagmap-admin/src/main/resources/static
