spring:
  mvc:
    view:
      suffix: .html
  resources:
    static-locations:
      - file:hashtagmap-admin/src/main/resources/static
  profiles:
    include: >
      kakao,
      kakao-security,
      db
    active: local
---
spring:
  profiles: local
  resources:
    static-locations:
      - file:hashtagmap-admin/src/main/resources/static
  mvc:
    view:
      suffix: .html