spring:
  mvc:
    view:
      suffix: .html
  profiles:
    include: >
      db
server:
  port: 9000
---
spring:
  profiles: set1
server:
  port: 9001
---
spring:
  profiles: set2
server:
  port: 9002
